version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  worker:
    build:
      context: ./worker
      dockerfile: ./worker/Dockerfile
    volumes:
      - ./worker:/app
    environment:
      - CELERY_DEV_MODE=true
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  backend_cache:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
